exclude:
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
  - config
  - config.rb
  - config_prod.rb
  - sass
lsi: false
pygments: true
safe: true
url: 'http://zacstewart.com'
markdown: redcarpet
