exclude:
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
  - config
  - config.rb
  - config_prod.rb
  - sass
include:
  - .well-known
lsi: false
highlighter: pygments
safe: true
url: 'http://zacstewart.com'
markdown: redcarpet
redcarpet:
  extensions:
    - tables
