exclude:
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - config
  - config.rb
  - config_prod.rb
  - sass
lsi: false
pygments: true
safe: true
url: 'http://zacstewart.com'
excerpt_separator: ''
markdown: redcarpet
